In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [17]:
dframe_wine = pd.read_csv('winequality-red.csv', sep=';')
dframe_wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11,34,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25,67,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15,54,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17,60,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11,34,0.9978,3.51,0.56,9.4,5

In [28]:
dframe_wine_q3 = dframe_wine[dframe_wine.quality == 3]

In [29]:
dframe_wine_q3_sorted = dframe_wine_q3.sort('alcohol', ascending=False)
dframe_wine_q3_sorted.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
899,8.3,1.020,0.02,3.40,0.084,6,11,0.99892,3.48,0.49,11.00,3
1299,7.6,1.580,0.00,2.10,0.137,5,9,0.99476,3.50,0.40,10.90,3
690,7.4,1.185,0.00,4.25,0.097,5,14,0.99660,3.63,0.54,10.70,3
1478,7.1,0.875,0.05,5.70,0.082,3,14,0.99808,3.40,0.52,10.20,3
1505,6.7,0.760,0.02,1.80,0.078,6,12,0.99600,3.55,0.63,9.95,3

In [31]:
dframe_wine_q3_sorted['alc_content_rank'] = np.arange(10) + 1
dframe_wine_q3_sorted

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,alc_content_rank
899,8.3,1.020,0.02,3.40,0.084,6,11,0.99892,3.48,0.49,11.00,3,1
1299,7.6,1.580,0.00,2.10,0.137,5,9,0.99476,3.50,0.40,10.90,3,2
690,7.4,1.185,0.00,4.25,0.097,5,14,0.99660,3.63,0.54,10.70,3,3
1478,7.1,0.875,0.05,5.70,0.082,3,14,0.99808,3.40,0.52,10.20,3,4
1505,6.7,0.760,0.02,1.80,0.078,6,12,0.99600,3.55,0.63,9.95,3,5
832,10.4,0.440,0.42,1.50,0.145,34,48,0.99832,3.38,0.86,9.90,3,6
1374,6.8,0.815,0.00,1.20,0.267,16,29,0.99471,3.32,0.51,9.80,3,7
1469,7.3,0.980,0.05,2.10,0.061,20,49,0.99705,3.31,0.55,9.70,3,8
459,11.6,0.580,0.66,2.20,0.074,10,47,1.00080,3.25,0.57,9.00,3,9
517,10.4,0.610,0.49,2.10,0.200,5,16,0.99940,3.16,0.63,8.40,3,10

In [32]:
def ranker(df):
    print('Lengh of dframe {}: {}'.format(df.__name__, len(df)))
    df['alc_content_rank'] = np.arange(len(df)) + 1
    return df

In [33]:
dframe_wine.sort('alcohol', ascending=False, inplace=True)
dframe_wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
652,15.9,0.36,0.65,7.5,0.096,22,71,0.99760,2.98,0.84,14.9,5
588,5.0,0.42,0.24,2.0,0.060,19,50,0.99170,3.72,0.74,14.0,8
142,5.2,0.34,0.00,1.8,0.050,27,63,0.99160,3.68,0.79,14.0,6
144,5.2,0.34,0.00,1.8,0.050,27,63,0.99160,3.68,0.79,14.0,6
1270,5.0,0.38,0.01,1.6,0.048,26,60,0.99084,3.70,0.75,14.0,6

In [8]:
dframe_wine = dframe_wine.groupby('quality').apply(ranker)

In [12]:
dframe_wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,alc_content_rank
652,15.9,0.36,0.65,7.5,0.096,22,71,0.99760,2.98,0.84,14.9,5,1
588,5.0,0.42,0.24,2.0,0.060,19,50,0.99170,3.72,0.74,14.0,8,1
142,5.2,0.34,0.00,1.8,0.050,27,63,0.99160,3.68,0.79,14.0,6,1
144,5.2,0.34,0.00,1.8,0.050,27,63,0.99160,3.68,0.79,14.0,6,2
1270,5.0,0.38,0.01,1.6,0.048,26,60,0.99084,3.70,0.75,14.0,6,3

In [13]:
num_of_qual = dframe_wine['quality'].value_counts()

In [14]:
num_of_qual

5    681
6    638
7    199
4     53
8     18
3     10
dtype: int64

In [15]:
dframe_wine[dframe_wine.alc_content_rank == 1].head(len(num_of_qual))

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,alc_content_rank
652,15.9,0.36,0.65,7.5,0.096,22,71,0.99760,2.98,0.84,14.9,5,1
588,5.0,0.42,0.24,2.0,0.060,19,50,0.99170,3.72,0.74,14.0,8,1
142,5.2,0.34,0.00,1.8,0.050,27,63,0.99160,3.68,0.79,14.0,6,1
821,4.9,0.42,0.00,2.1,0.048,16,42,0.99154,3.71,0.74,14.0,7,1
45,4.6,0.52,0.15,2.1,0.054,8,65,0.99340,3.90,0.56,13.1,4,1
899,8.3,1.02,0.02,3.4,0.084,6,11,0.99892,3.48,0.49,11.0,3,1